["Documents/Scripts/modules.d/test-sandbox.psm1"]
	type = "file"
	url = "https://raw.githubusercontent.com/JohnEricson/test-sandbox/main/test-sandbox.psm1"
	refreshPeriod = "168h"
["Documents/Scripts/modules.d/git_aliases.psm1"]
	type = "file"
	url = "https://raw.githubusercontent.com/JohnEricson/git_aliases/main/git_aliases.psm1"
	refreshPeriod = "168h"
